models.py
from app import db
from datetime import datetime
import re
# Flask Security
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

post_tags = db.Table('post_tags',
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                    )

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now)
    image = db.Column(db.String(120), default='image.jpg')
    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))
    
    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.name:
            self.slug = slugify(self.name)


    def __repr__(self):
        return '<Tag id: {}, title: {}>'.format(self.id, self.name)

#### Flask Ssecurity #####
roles_users = db.Table('roles_users',
                        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                        db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
                        )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField, FileField
from wtforms.validators import InputRequired

class PostForm(Form):
    title = StringField('Title', [InputRequired()])
    body = TextAreaField('Body')
    image = FileField('Image')
    

app.py
import os
from flask import Flask, request
from flask_sqlalchemy import SQLAlchemy
#create admin
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
#flask security, the storage of users, roles
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security


app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

import view
from posts.blueprint import posts
app.register_blueprint(posts, url_prefix='/blog') #registration posts app(blueprint)
###  Admin  ####
from models import *
#integration Admin and Flask Security
from flask_security import current_user
from flask import redirect, url_for, request
class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')
    
    def inaccessible_callback(self, name, **kwargs):
        #localhost/admin/
        return redirect(url_for('security.login', next=request.url))

#Point to admin panel to use our class-constructors
#Allows our to change slug at the moment creating or editing Post from admin Panel
class BaseModelView(ModelView):
    def on_model_change(self, form, model , is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

#class constrains allow to models POst and Tag in AdminPanel
class AdminView(AdminMixin, ModelView):
    pass

#class constrains allow to AdminPanel at all
from flask_admin import AdminIndexView
class HomeAdminView(AdminMixin, AdminIndexView):
    pass

class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags', 'image']

class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']

admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session)) #before was ModelView instead of AdminView --->PostAdminView
admin.add_view(TagAdminView(Tag, db.session))
## flask security ##
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post, Tag
from flask import request
from .forms import PostForm
from app import db
from flask import redirect
from flask import url_for
#Flask security
from flask_security import login_required
#for photo
import secrets
import os
from flask import current_app
from sqlalchemy import func

posts = Blueprint('posts', __name__, template_folder='templates') # realization functionality of app posts

def save_image(photo):
    hash_photo = secrets.token_urlsafe(10)
    print(hash_photo)
    _, file_extension = os.path.splitext(photo.filename)
    print(file_extension)
    photo_name = hash_photo + file_extension
    file_path = os.path.join(current_app.root_path, 'static/img', photo_name)
    photo.save(file_path)
    print('hello')
    return photo_name

@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        if request.form['title']:
            title = request.form['title']
            body = request.form['body']
            photo = save_image(request.files.get('image'))
            try:
                post = Post(title=title, body=body, image=photo)
                db.session.add(post)
                db.session.commit()
            except:
                print('Something wrong!')
            return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/create_post.html', form=form)

@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)

@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        post = Post.query.filter(func.lower(Post.title).contains(q.lower(), autoescape=True) | \
            func.lower(Post.body).contains(q.lower(), autoescape=True)) #.all() func.lower(Post.title) == func.lower(q)
    else:
        post = Post.query.order_by(Post.created.desc())  #method disc() orders lists of posts down

    pages = post.paginate(page=page, per_page=3)

    return render_template('posts/index.html', pages=pages)

@posts.route('/<slug>/')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404() #or first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all() # get list and not basequery (take function all())
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
    Create New Post
{% endblock %}

{% block content_title %}
    New Post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.create_post') }}" method="POST" enctype="multipart/form-data">
            {% for field in form %}
            <div class="form-group">
                {{ field.label(class="control-label") }}
                {{ field(class="form-control") }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-secondary">Create</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}
{% block title %}
    Edit Post
{% endblock %}

{% block content_title %}
    Edit Post
{% endblock %}

{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
            {% for field in form %}
            <div class="form-group">
                {{ field.label(class="control-label") }}
                {{ field(class="form-control") }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-secondary">Edit Post</button>
        </form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Blueprint Index Page
{% endblock %}

{% block content_title %}
Posts
{% endblock %}

{% block content %}

{% for p in pages.items %}
<!-- was for p in post-->
<div class="card mb-4">
    {% if p.image %}
    <img class="card-img-top" src="{{ url_for('static', filename='img') }}/{{ p.image }}" alt="Card image cap">
    {% else %}
    <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
    {% endif %}
  <div class="card-body">

    <h2 class="card-title">
      {{ p.title }}
      <!-- <a href="{{ url_for('posts.post_detail', slug=p.slug) }}">{{ p.title }}</a> -->
    </h2>

    <p class="card-text">
      {{ p.body|truncate(100) }}
    </p>
    <a href="{{ url_for('posts.post_detail', slug=p.slug) }}" class="btn btn-primary">Read More &rarr;</a>
  </div>

  <div class="card-footer text-muted">
    Posted on {{ p.created.strftime('%Y-%m-%d') }}, by
    <a href="#">FlaskApp</a>
  </div>
</div>
{% endfor %}

<nav aria-label="...">
  <ul class="pagination">

    <li {% if not pages.has_prev%} class="page-item disabled" {% endif %}>

      <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% for page in pages.iter_pages() %}

    <li {% if page == pages.page %} class="page-item active" aria-current="page" {% endif %}>
      <a class="page-link" href="./?page={{ page }}">{{ page }}<span class="sr-only">(current)</span></a>
    </li>

    {% endfor %}

    <li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
      <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
    </li>
  </ul>
</nav>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
    <div class="tags">
        {% for tag in tags %}
        <a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}" class="badge badge-secondary">{{ tag.name }}</a>
        {% endfor %}
    </div>
    <div class="my-4">
        <img class="card-img-top" src="{{ url_for('static', filename='img') }}/{{ post.image }}" alt="Card image cap">
    </div>
{% endblock %}

{% block content %}
    {{ post.body }}
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/blog-home.css') }}">
  <title>

    {% block title %}

    {% endblock %} | Flask app

  </title>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for ('index') }}">FlaskApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for ('index') }}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">

          {% block content_title %}

          {% endblock %}
          <!-- <small>Secondary Text</small> -->
        </h1>

        <!-- Blog Post -->
        {% block content %}

        {% endblock %}
        
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            
              <form class="navbar-form navbar-left" method="GET">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.args.get('q', '') }}">
                </div>

                <button formaction="{{ url_for ('posts.index') }}" type="submit" class="btn btn-secondary" type="button">Submit</button>                  
              </form>
            
          </div>
        </div>

        <!-- Categories Widget -->
        
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark my-4">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; FlaskApp 2019</p>
    </div>
    <!-- /.container -->
  </footer>

<!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  
</body>

</html>

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %}
      Login
{% endblock %}

{% block content_title %}
  <span class="col-md-offset-3 col-md-6">
        {{ _('Login') }}
  </span>
{% endblock %}

{% block content %}

  <div class="col-md-offset-3 col-md-6">
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    {% include "security/_messages.html" %}
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
      {{ login_user_form.hidden_tag() }}
      {{ render_field_with_errors(login_user_form.email, class="form-control") }}
      {{ render_field_with_errors(login_user_form.password, class="form-control") }}
      {{ render_field_with_errors(login_user_form.remember) }}
      {{ render_field(login_user_form.next) }}
      {{ render_field(login_user_form.submit, class="btn btn-success") }}
    </form>
    {% include "security/_menu.html" %}
  </div>

{% endblock %}